site_name: Net
site_author: drake
site_description: Net document
copyright: Copyright &copy; 2018 - 2020 劉強東

repo_name: GitHub
repo_url: https://github.com/liangjingkanji/Net

extra_css:
  - css/extra.css

docs_dir: docs

theme:
  name: material
  custom_dir: docs/material
  palette:
    scheme: drake
    primary: white
  font: false
  language: 'zh'
  features:
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

nav:
  - 使用: index.md
  - 协程请求: coroutine-request.md
  - 作用域: scope.md
  - 同步请求: sync-request.md
  - 请求参数: request.md
  - 全局配置: config.md
  - 响应数据:
      - 默认转换器: default-converter.md
      - 自定义转换器: converter.md
      - 特殊结构解析: convert-special.md
      - kotlin-serialization: kotlin-serialization.md
      - 数据模型生成插件: model-generate.md
  - 自动化:
      - 自动加载框: auto-dialog.md
      - 自动缺省页: auto-state.md
      - 自动下拉刷新: auto-refresh.md
      - 自动分页加载: auto-page.md
  - 切换线程: switch-thread.md
  - ViewModel: view-model.md
  - 异常追踪: exception-track.md
  - 错误处理:
      - 默认错误处理: error-default.md
      - 单例错误捕获: error-single.md
      - 全局错误捕获: error-global.md
      - 自定义错误提示: error-tip.md
      - 自定义异常: error-exception.md
  - OkHttpClient: okhttp-client.md
  - 拦截器: interceptor.md
  - Https证书: https.md
  - Cookie管理: cookie.md
  - 缓存: cache.md
  - 标签/额外数据: tag.md
  - 上传文件: upload-file.md
  - 下载文件: download-file.md
  - 进度监听: progress.md
  - 取消请求: cancel.md
  - 重复请求: unique.md
  - 自动搜索/筛选: debounce.md
  - 最快请求结果: fastest.md
  - 日志插件: log-recorder.md
  - 通知栏日志: log-notice.md
  - 限时/定时请求: timing.md
  - Callback: callback.md
  - 轮询器/倒计时: interval.md
  - 社区讨论: https://github.com/liangjingkanji/Net/discussions
  - 常见问题: https://github.com/liangjingkanji/Net/blob/master/docs/issues.md
  - 更新日志: updates.md
  - 3.x文档: api/index.html
